config/routes.rb
Noelle::Application.routes.draw do

  devise_for :users

  namespace :admin do
    resources :categories do
      as_routes
    end
    resources :projects do
      as_routes
    end
    resources :pictures do
      as_routes
    end
    resources :pages do
      as_routes
    end
    resources :translations do
      as_routes
    end
    resources :users do
      as_routes
    end
    resources :subscribers do
      as_routes
    end
    resources :images do
      as_routes
    end
    root :to => "categories#index"
  end

  resources :categories, :only => [:index, :show] do
    resources :projects, :only => [:show] do
      member do
        get :comment
      end
    end
  end

  resources :attachments, :only => :show
  resources :subscribers, :only => :create

  match ':name' => 'pages#show', :as => :page
  root :to => 'pages#index'
  

end

app/models/attachment.rb
# -*- encoding : utf-8 -*-
class Attachment < ActiveRecord::Base

  has_attached_file :file,
                    :url => "/system/:attachment/:id/:style/:filename"

end

app/models/category.rb
# -*- encoding : utf-8 -*-
class Category < ActiveRecord::Base

  has_many :projects, :dependent => :destroy
  
  has_many :pictures, :through => :projects

  order_collection_by :position, :asc

  scope :displayable, where(:display => true)
end

app/models/image.rb
# -*- encoding : utf-8 -*-
class Image < Attachment

  has_attached_file :file,
                    :styles => {:small => "30x30!"},
                    :url => "/system/:attachment/:id/:style/:filename"
end

app/models/page.rb
# -*- encoding : utf-8 -*-
class Page < ActiveRecord::Base

  cache_constants :name

  has_attached_file :image,
                    :styles => { :small => "30x30!", :large => "277x513!" },
                    :url => "/system/:attachment/:id/:style/:filename"

  has_attached_file :picture,
                    :styles => { :small => "30x30!", :large => "x60>"},
                    :url => "/system/:attachment/:id/:style/:filename"

  has_attached_file :document,
                    :url => "/system/:attachment/:id/:style/:filename"

  has_attached_file :document_2,
                    :url => "/system/:attachment/:id/:style/:filename"


end

app/models/picture.rb
# -*- encoding : utf-8 -*-
class Picture < ActiveRecord::Base

  has_attached_file :image,
                    :styles => { :small => "30x30!", :thumb => "x55" },
                    :url => "/system/:attachment/:id/:style/:filename"

  belongs_to :project

  order_collection_by :position, :asc, :parent => :project

  scope :top, where(:top => true)
end

app/models/project.rb
# -*- encoding : utf-8 -*-
class Project < ActiveRecord::Base

  belongs_to :category
  has_many :pictures, :dependent => :destroy

  order_collection_by :position, :asc, :parent => :category

  scope :displayable, where(:display => true)
end

app/models/subscriber.rb
# -*- encoding : utf-8 -*-
class Subscriber < ActiveRecord::Base

  after_save :send_report

  validates_presence_of :name, :email

  validates_uniqueness_of :email, :unless => "email.blank?"

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :allow_blank => true

  def send_report
    Newsletter.report(self).deliver
  end

end

app/models/translation.rb
# -*- encoding : utf-8 -*-
class Translation < Attachment

  order_collection_by :position, :asc
  
  scope :displayable, where(:display => true)
  
end

app/models/user.rb
# -*- encoding : utf-8 -*-
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :recoverable, :rememberable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  def self.with(options={})
    where(options)
  end

  def to_label
    email
  end
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery

  layout :layout_by_resource

  def layout_by_resource
    if devise_controller?
      "authentication.html.haml"
    else
      "application"
    end
  end


end

app/controllers/attachments_controller.rb
# -*- encoding : utf-8 -*-
class AttachmentsController < ApplicationController

  def show
    @attachment = Attachment.find(params[:id])
    send_file @attachment.file.path, :disposition  =>  'attachment', :type => @attachment.file_content_type
  end
end

app/controllers/categories_controller.rb
# -*- encoding : utf-8 -*-
class CategoriesController < ApplicationController

  def index
    @pictures = Picture.top.shuffle
  end
  def show
    @category = Category.find_by_id(params[:id])
  end
end

app/controllers/pages_controller.rb
# -*- encoding : utf-8 -*-
class PagesController < ApplicationController

  def index
    @pictures = Picture.top.shuffle
    @translations = Translation.displayable    
  end

  def show
    @page = Page.find_by_name(params[:name])
    redirect_to root_path unless @page
  end
  
end

app/controllers/projects_controller.rb
# -*- encoding : utf-8 -*-
class ProjectsController < ApplicationController
  before_filter :get_category

  def get_category
    @category = Category.find_by_id(params[:category_id])
  end

  def show
    @project = Project.find_by_id(params[:id])
  end

  def comment
    @project = Project.find_by_id(params[:id])
  end
  
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
end

app/helpers/attachments_helper.rb
# -*- encoding : utf-8 -*-
module AttachmentsHelper
end

app/helpers/categories_helper.rb
# -*- encoding : utf-8 -*-
module CategoriesHelper
end

app/helpers/pages_helper.rb
# -*- encoding : utf-8 -*-
module PagesHelper
end

app/helpers/projects_helper.rb
# -*- encoding : utf-8 -*-
module ProjectsHelper
end

app/helpers/subscribers_helper.rb
# -*- encoding : utf-8 -*-
module SubscribersHelper
end

app/views/admin/pages/_content_column.html.haml
= content_column(record)

app/views/admin/pages/_content_form_column.html.haml
= text_area :record, :content, :style => "width:100%;", :class => 'mce'

app/views/layouts/admin.html.haml
!!! XML
!!!
%html
  %head
    = stylesheet_link_tag 'admin'
    = javascript_include_tag 'admin'
    %meta{ "http-equiv" => "content-type", :content => "text/html;charset=UTF-8" }
    = csrf_meta_tag
  %html
    #page
      #banner
        %h1 ::ADMIN
        #user_links
          %span= current_user.email
          = link_to "Log out", destroy_user_session_path, :method => :delete
      #content
        #tabs
          %ul
            %li= link_to content_tag(:span, "Categories & projets"), admin_categories_path
            %li= link_to content_tag(:span, "Pages"), admin_pages_path, :title => "pages_cont"
            %li= link_to content_tag(:span, "Utilisateurs"), admin_users_path
            %li= link_to content_tag(:span, "Abonnes"), admin_subscribers_path
            %li= link_to content_tag(:span, "Traductions"), admin_translations_path
            %li= link_to content_tag(:span, "Images inserables"), admin_images_path
          #pages_cont= yield

app/views/layouts/application.html.haml
!!! XML
!!!
%html
  %head
    = javascript_include_tag 'application'

    -#= javascript_include_tag 'jquery.min', 'mousewheel.js', 'scrollpane.js', 'galleria/src/galleria', 'rails_jquery', 'jquery.effects.core', 'jquery.effects.highlight', 'website', :cache => 'application_all'
    
    = stylesheet_link_tag 'scrollpane', 'application'
    %meta{ "http-equiv" => "content-type", :content => "text/html;charset=UTF-8" }

    / [if lt IE 8]
      = stylesheet_link_tag 'compiled/ie'

    
  %body{ :class => params[:controller] }
    #banner

    #page{:class => "#{params[:action]} #{params[:name]}"}
      #top_banner
        %h1
          = link_to root_path do
            Noëlle Echiffre
            %span Photographe

        %ul#menu
          %li= menu_link_to "accueil", root_path, true
          %li= menu_link_to "les séries", categories_path, true, Proc.new{ ['categories', 'projects'].include?(params[:controller])}
          %li= menu_link_to "la démarche de l'artiste", page_path(:name => Page::DEMARCHE.name), true
          %li= menu_link_to "les actualités", page_path(:name => Page::ACTUALITES.name), true
          %li= menu_link_to "la digigraphie", page_path(:name => Page::DIGIGRAPHIE.name), true
          %li= menu_link_to "liens", page_path(:name => Page::LIENS.name), true
          %li= menu_link_to "contact ", page_path(:name => Page::CONTACT.name)

        = yield(:back)

      #side_content_wrapper
        #side_content= yield(:side_content)
      #main_content_wrapper
        #main_content= yield

      #footer
        #copyright © Copyright Noëlle Echiffre

      #thumbs

app/views/layouts/authentication.html.haml
%html
  %head
    = stylesheet_link_tag 'authentication'
    = csrf_meta_tag
  %html
    #page
      #banner
        %h1 Noelle::ADMIN
        #notice
          = flash[:notice]
          = flash[:warning]
          = flash[:error]

      #content
        = yield

app/views/newsletter/report.text.erb
Nom : <%= @subscriber.name %>
email : <%= @subscriber.email %>

app/views/pages/index.html.haml
- content_for :side_content do
  %h2 Other Languages
  %ul
    - @translations.each do |translation|
      %li= link_to(translation.language, translation.file.url, :target => '_blank')

  =render :partial => 'subscribers/new'

= render :partial => 'pictures/gallery', :locals => { :pictures => @pictures }

app/views/pages/show.html.haml
- content_for :side_content do
  = image_tag @page.image.url('large'), :alt => "", :title => "" 
  
#page_content
  %div
    = image_tag @page.picture.url(:large), :class => 'attached_picture' if @page.picture?
    = raw @page.content
    = link_to @page.document.original_filename, @page.document.url, :alt => "Download #{@page.document.original_filename}", :target => '_blank', :class => "attached_document #{@page.document.content_type.match(/pdf/) ? 'pdf' : 'img'}" if @page.document?
    = link_to @page.document_2.original_filename, @page.document_2.url, :alt => "Download #{@page.document_2.original_filename}", :target => '_blank', :class => "attached_document #{@page.document.content_type.match(/pdf/) ? 'pdf' : 'img'}" if @page.document_2?